Warning: k_diffusion not found at path /home/lihao/git/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/sampling.py
/home/lihao/mambaforge-pypy3/envs/SD_web/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/home/lihao/mambaforge-pypy3/envs/SD_web/lib/python3.10/site-packages/torchvision/image.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKSs'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
Error setting up CodeFormer:
Traceback (most recent call last):
  File "/home/lihao/git/stable-diffusion-webui/modules/codeformer_model.py", line 37, in setup_model
    from facelib.utils.face_restoration_helper import FaceRestoreHelper
  File "/home/lihao/git/stable-diffusion-webui/repositories/CodeFormer/facelib/utils/face_restoration_helper.py", line 7, in <module>
    from facelib.detection import init_detection_model
  File "/home/lihao/git/stable-diffusion-webui/repositories/CodeFormer/facelib/detection/__init__.py", line 10, in <module>
    from .retinaface.retinaface import RetinaFace
  File "/home/lihao/git/stable-diffusion-webui/repositories/CodeFormer/facelib/detection/retinaface/retinaface.py", line 14, in <module>
    from basicsr.utils.misc import get_device
ImportError: cannot import name 'get_device' from 'basicsr.utils.misc' (/home/lihao/mambaforge-pypy3/envs/SD_web/lib/python3.10/site-packages/basicsr/utils/misc.py)

No module 'xformers'. Proceeding without it.
2024-06-11 21:55:12,542 - ControlNet - [0;32mINFO[0m - ControlNet v1.1.219
ControlNet preprocessor location: /home/lihao/git/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/downloads
2024-06-11 21:55:12,604 - ControlNet - [0;32mINFO[0m - ControlNet v1.1.219
Loading weights [7f96a1a9ca] from /home/lihao/git/stable-diffusion-webui/models/Stable-diffusion/anything-v5-PrtRE.safetensors
Warning: k_diffusion not found at path /home/lihao/git/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/sampling.py
/home/lihao/mambaforge-pypy3/envs/SD_web/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/home/lihao/mambaforge-pypy3/envs/SD_web/lib/python3.10/site-packages/torchvision/image.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKSs'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
Error setting up CodeFormer:
Traceback (most recent call last):
  File "/home/lihao/git/stable-diffusion-webui/modules/codeformer_model.py", line 37, in setup_model
    from facelib.utils.face_restoration_helper import FaceRestoreHelper
  File "/home/lihao/git/stable-diffusion-webui/repositories/CodeFormer/facelib/utils/face_restoration_helper.py", line 7, in <module>
    from facelib.detection import init_detection_model
  File "/home/lihao/git/stable-diffusion-webui/repositories/CodeFormer/facelib/detection/__init__.py", line 10, in <module>
    from .retinaface.retinaface import RetinaFace
  File "/home/lihao/git/stable-diffusion-webui/repositories/CodeFormer/facelib/detection/retinaface/retinaface.py", line 14, in <module>
    from basicsr.utils.misc import get_device
ImportError: cannot import name 'get_device' from 'basicsr.utils.misc' (/home/lihao/mambaforge-pypy3/envs/SD_web/lib/python3.10/site-packages/basicsr/utils/misc.py)

No module 'xformers'. Proceeding without it.
2024-06-11 21:58:36,480 - ControlNet - [0;32mINFO[0m - ControlNet v1.1.219
ControlNet preprocessor location: /home/lihao/git/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/downloads
2024-06-11 21:58:36,544 - ControlNet - [0;32mINFO[0m - ControlNet v1.1.219
Loading weights [7f96a1a9ca] from /home/lihao/git/stable-diffusion-webui/models/Stable-diffusion/anything-v5-PrtRE.safetensors
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /home/lihao/mambaforge-pypy3/envs/SD_web/lib/python3.10/site-packages/gradio │
│ /networking.py:118 in start_server                                           │
│                                                                              │
│   115 │   │   try:                                                           │
│   116 │   │   │   s = socket.socket()                                        │
│   117 │   │   │   s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)    │
│ ❱ 118 │   │   │   s.bind((LOCALHOST_NAME, server_port))                      │
│   119 │   │   │   s.close()                                                  │
│   120 │   │   except OSError as err:                                         │
│   121 │   │   │   raise OSError(                                             │
╰──────────────────────────────────────────────────────────────────────────────╯
OSError: [Errno 98] Address already in use

The above exception was the direct cause of the following exception:

╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /home/lihao/git/stable-diffusion-webui/webui.py:478 in <module>              │
│                                                                              │
│   475 │   if cmd_opts.nowebui:                                               │
│   476 │   │   api_only()                                                     │
│   477 │   else:                                                              │
│ ❱ 478 │   │   webui()                                                        │
│   479                                                                        │
│                                                                              │
│ /home/lihao/git/stable-diffusion-webui/webui.py:395 in webui                 │
│                                                                              │
│   392 │   │   │   FastAPI.original_setup = FastAPI.setup                     │
│   393 │   │   │   FastAPI.setup = fastapi_setup                              │
│   394 │   │                                                                  │
│ ❱ 395 │   │   app, local_url, share_url = shared.demo.launch(                │
│   396 │   │   │   share=cmd_opts.share,                                      │
│   397 │   │   │   server_name=server_name,                                   │
│   398 │   │   │   server_port=26897,                                         │
│                                                                              │
│ /home/lihao/mambaforge-pypy3/envs/SD_web/lib/python3.10/site-packages/gradio │
│ /blocks.py:1743 in launch                                                    │
│                                                                              │
│   1740 │   │   │   │   │   "Rerunning server... use `close()` to stop if you │
│   1741 │   │   │   │   )                                                     │
│   1742 │   │   else:                                                         │
│ ❱ 1743 │   │   │   server_name, server_port, local_url, app, server = networ │
│   1744 │   │   │   │   self,                                                 │
│   1745 │   │   │   │   server_name,                                          │
│   1746 │   │   │   │   server_port,                                          │
│                                                                              │
│ /home/lihao/mambaforge-pypy3/envs/SD_web/lib/python3.10/site-packages/gradio │
│ /networking.py:121 in start_server                                           │
│                                                                              │
│   118 │   │   │   s.bind((LOCALHOST_NAME, server_port))                      │
│   119 │   │   │   s.close()                                                  │
│   120 │   │   except OSError as err:                                         │
│ ❱ 121 │   │   │   raise OSError(                                             │
│   122 │   │   │   │   f"Port {server_port} is in use. If a gradio.Blocks is  │
│   123 │   │   │   │   f"you can close() it or gradio.close_all()."           │
│   124 │   │   │   ) from err                                                 │
╰──────────────────────────────────────────────────────────────────────────────╯
OSError: Port 26897 is in use. If a gradio.Blocks is running on the port, you 
can close() it or gradio.close_all().
Creating model from config: /home/lihao/git/stable-diffusion-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying optimization: sdp-no-mem... done.
Textual inversion embeddings loaded(0): 
Model loaded in 2.8s (load weights from disk: 0.6s, create model: 0.3s, apply weights to model: 1.1s, apply half(): 0.4s, move model to device: 0.4s).
Warning: k_diffusion not found at path /home/lihao/git/stable-diffusion-webui/repositories/k-diffusion/k_diffusion/sampling.py
/home/lihao/mambaforge-pypy3/envs/SD_web/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/home/lihao/mambaforge-pypy3/envs/SD_web/lib/python3.10/site-packages/torchvision/image.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKSs'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
Error setting up CodeFormer:
Traceback (most recent call last):
  File "/home/lihao/git/stable-diffusion-webui/modules/codeformer_model.py", line 37, in setup_model
    from facelib.utils.face_restoration_helper import FaceRestoreHelper
  File "/home/lihao/git/stable-diffusion-webui/repositories/CodeFormer/facelib/utils/face_restoration_helper.py", line 7, in <module>
    from facelib.detection import init_detection_model
  File "/home/lihao/git/stable-diffusion-webui/repositories/CodeFormer/facelib/detection/__init__.py", line 10, in <module>
    from .retinaface.retinaface import RetinaFace
  File "/home/lihao/git/stable-diffusion-webui/repositories/CodeFormer/facelib/detection/retinaface/retinaface.py", line 14, in <module>
    from basicsr.utils.misc import get_device
ImportError: cannot import name 'get_device' from 'basicsr.utils.misc' (/home/lihao/mambaforge-pypy3/envs/SD_web/lib/python3.10/site-packages/basicsr/utils/misc.py)

No module 'xformers'. Proceeding without it.
2024-06-11 22:00:02,126 - ControlNet - [0;32mINFO[0m - ControlNet v1.1.219
ControlNet preprocessor location: /home/lihao/git/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/downloads
2024-06-11 22:00:02,182 - ControlNet - [0;32mINFO[0m - ControlNet v1.1.219
Loading weights [7f96a1a9ca] from /home/lihao/git/stable-diffusion-webui/models/Stable-diffusion/anything-v5-PrtRE.safetensors
╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /home/lihao/mambaforge-pypy3/envs/SD_web/lib/python3.10/site-packages/gradio │
│ /networking.py:118 in start_server                                           │
│                                                                              │
│   115 │   │   try:                                                           │
│   116 │   │   │   s = socket.socket()                                        │
│   117 │   │   │   s.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)    │
│ ❱ 118 │   │   │   s.bind((LOCALHOST_NAME, server_port))                      │
│   119 │   │   │   s.close()                                                  │
│   120 │   │   except OSError as err:                                         │
│   121 │   │   │   raise OSError(                                             │
╰──────────────────────────────────────────────────────────────────────────────╯
OSError: [Errno 98] Address already in use

The above exception was the direct cause of the following exception:

╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /home/lihao/git/stable-diffusion-webui/webui.py:478 in <module>              │
│                                                                              │
│   475 │   if cmd_opts.nowebui:                                               │
│   476 │   │   api_only()                                                     │
│   477 │   else:                                                              │
│ ❱ 478 │   │   webui()                                                        │
│   479                                                                        │
│                                                                              │
│ /home/lihao/git/stable-diffusion-webui/webui.py:395 in webui                 │
│                                                                              │
│   392 │   │   │   FastAPI.original_setup = FastAPI.setup                     │
│   393 │   │   │   FastAPI.setup = fastapi_setup                              │
│   394 │   │                                                                  │
│ ❱ 395 │   │   app, local_url, share_url = shared.demo.launch(                │
│   396 │   │   │   share=cmd_opts.share,                                      │
│   397 │   │   │   server_name=server_name,                                   │
│   398 │   │   │   server_port=26897,                                         │
│                                                                              │
│ /home/lihao/mambaforge-pypy3/envs/SD_web/lib/python3.10/site-packages/gradio │
│ /blocks.py:1743 in launch                                                    │
│                                                                              │
│   1740 │   │   │   │   │   "Rerunning server... use `close()` to stop if you │
│   1741 │   │   │   │   )                                                     │
│   1742 │   │   else:                                                         │
│ ❱ 1743 │   │   │   server_name, server_port, local_url, app, server = networ │
│   1744 │   │   │   │   self,                                                 │
│   1745 │   │   │   │   server_name,                                          │
│   1746 │   │   │   │   server_port,                                          │
│                                                                              │
│ /home/lihao/mambaforge-pypy3/envs/SD_web/lib/python3.10/site-packages/gradio │
│ /networking.py:121 in start_server                                           │
│                                                                              │
│   118 │   │   │   s.bind((LOCALHOST_NAME, server_port))                      │
│   119 │   │   │   s.close()                                                  │
│   120 │   │   except OSError as err:                                         │
│ ❱ 121 │   │   │   raise OSError(                                             │
│   122 │   │   │   │   f"Port {server_port} is in use. If a gradio.Blocks is  │
│   123 │   │   │   │   f"you can close() it or gradio.close_all()."           │
│   124 │   │   │   ) from err                                                 │
╰──────────────────────────────────────────────────────────────────────────────╯
OSError: Port 26897 is in use. If a gradio.Blocks is running on the port, you 
can close() it or gradio.close_all().
Creating model from config: /home/lihao/git/stable-diffusion-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying optimization: sdp-no-mem... done.
Textual inversion embeddings loaded(0): 
Model loaded in 2.4s (load weights from disk: 0.6s, create model: 0.3s, apply weights to model: 0.7s, apply half(): 0.4s, move model to device: 0.4s).

Thanks for being a Gradio user! If you have questions or feedback, please join our Discord server and chat with us: https://discord.gg/feTf9x3ZSB
Running on local URL:  http://127.0.0.1:26897

To create a public link, set `share=True` in `launch()`.
Startup time: 5.8s (import torch: 1.7s, import gradio: 1.0s, import ldm: 0.4s, other imports: 1.9s, load scripts: 0.4s, create ui: 0.2s, gradio launch: 0.1s).
Creating model from config: /home/lihao/git/stable-diffusion-webui/configs/v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying optimization: sdp-no-mem... done.
Textual inversion embeddings loaded(0): 
Model loaded in 2.4s (load weights from disk: 0.5s, create model: 0.3s, apply weights to model: 0.8s, apply half(): 0.4s, move model to device: 0.4s).
  0%|          | 0/20 [00:00<?, ?it/s]
Total progress:   0%|          | 0/20 [00:00<?, ?it/s][A  5%|▌         | 1/20 [00:02<00:50,  2.65s/it]
Total progress:  15%|█▌        | 3/20 [00:00<00:00, 18.17it/s][A 15%|█▌        | 3/20 [00:02<00:12,  1.34it/s]
Total progress:  25%|██▌       | 5/20 [00:00<00:00, 16.45it/s][A 25%|██▌       | 5/20 [00:02<00:05,  2.52it/s]
Total progress:  35%|███▌      | 7/20 [00:00<00:00, 15.89it/s][A 35%|███▌      | 7/20 [00:03<00:03,  3.89it/s]
Total progress:  45%|████▌     | 9/20 [00:00<00:00, 14.40it/s][A 45%|████▌     | 9/20 [00:03<00:02,  5.25it/s]
Total progress:  55%|█████▌    | 11/20 [00:00<00:00, 13.52it/s][A 55%|█████▌    | 11/20 [00:03<00:01,  6.55it/s]
Total progress:  65%|██████▌   | 13/20 [00:00<00:00, 12.49it/s][A 65%|██████▌   | 13/20 [00:03<00:00,  7.54it/s]
Total progress:  75%|███████▌  | 15/20 [00:01<00:00, 13.18it/s][A 75%|███████▌  | 15/20 [00:03<00:00,  8.97it/s]
Total progress:  85%|████████▌ | 17/20 [00:01<00:00, 13.69it/s][A 85%|████████▌ | 17/20 [00:03<00:00, 10.26it/s]
Total progress:  95%|█████████▌| 19/20 [00:01<00:00, 12.92it/s][A 95%|█████████▌| 19/20 [00:04<00:00, 10.61it/s]100%|██████████| 20/20 [00:04<00:00,  4.85it/s]

Total progress: 100%|██████████| 20/20 [00:01<00:00, 12.92it/s][ATotal progress: 100%|██████████| 20/20 [00:01<00:00, 12.09it/s]